rules:
  failed_login:
    patterns:
      - 'failed\s+password'
      - 'authentication\s+failure'
  sql_injection:
    patterns:
      - 'select.+from'
      - 'union\s+select'
      - 'or\s+1\s*=\s*1'
      - 'drop\s+table'
      - '--'
  ip_blacklist:
    - '46.118.125.84'
    - '217.12.185.5'

email:
  enabled: false
  sender_email: 'you@example.com'
  sender_password: 'yourpassword'
  recipient_email: 'admin@example.com'
  smtp_server: 'smtp.example.com'
  smtp_port: 587